### ISSUE TITLE
Users getting logged out with "Unsuccessful Refresh Token exchange, reused refresh token detected"

### ISSUE THREAD

**Issue by LA-Johan** [auth0/auth0-react#929]
### Checklist

- [x] The issue can be reproduced in the [auth0-react sample app](https://github.com/auth0-samples/auth0-react-samples/tree/master/Sample-01) (or N/A).
- [x] I have looked into the [Readme](https://github.com/auth0/auth0-react#readme), [Examples](https://github.com/auth0/auth0-react/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-react/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [x] I have looked into the [API documentation](https://auth0.github.io/auth0-react/) and have not found a suitable solution or answer.
- [x] I have searched the [issues](https://github.com/auth0/auth0-react/issues) and have not found a suitable solution or answer.
- [x] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [x] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Our usage of Auth0 is pretty simple. After the user has been logged in we just attach the access token to network calls and verify them server side. 

```
const useApi = (): Api => {
  const { getAccessTokenSilently } = useAuth0()
  const backend = axios.create({ baseURL: apiUri, timeout: 10000 })
  backend.interceptors.request.use(
    async config => {
      const accessToken = await getAccessTokenSilently()
      config.headers["Authorization"] = `Bearer ${accessToken}`
      return config
    },

    async error => {}
  )
}  
```
 
We have gotten user reports that they get error in title. Our understanding is that this error is unrecoverable so we log the user out and force them to re-authenticate. We have a couple of thousand weekly users and this happens to maybe 2% of them. 

One log id as an example:
90020251109193144192993000000000000001223372093304300940

Our top level provider:
```
 <Auth0Provider
        key={`${domain}-${clientId}-${audience}`} // This forces remount when values change
        domain={domain}
        clientId={clientId}
        authorizationParams={{
          redirect_uri: getFrontEndHost(),
          audience: audience,
        }}
        cacheLocation={"localstorage"}
        onRedirectCallback={onAuth0Redirect}
        useRefreshTokens={true}
      >
        <AppWithTheme />
</Auth0Provider>
```

### Reproduction

Seems to happen randomly, a few times a week for affected users. Mostly on iOS and MacOS devices but we've also seen it happen on Windows machines. 

### Additional context

A similar issue happens when we use the react native version, but only for iOS devices. We allow overlap for expiring refresh tokens (120 seconds). Our refresh token are set to last one year, and we're currently seeing this multiple times a week for users. 

### auth0-react version

2.8.0

### React version

19.1.0

### Which browsers have you tested in?

Chrome, Safari

**Comment by gyaneshgouraw** [comment]
Hey @LA-Johan , i am reviewing the issue. Once we have more updates, we will notify you.

**Comment by francosomosfin** [comment]
Hi @gyaneshgouraw-okta 

We are facing the same issue described by @LA-Johan .

We have a very simple Auth0 integration, and we get this error randomly several times a week, sometimes affecting the same user more than once a month.

We have a web application, and in addition to that, we use Capacitor to build our iOS and Android native apps. In the native apps, we use a custom cache that relies on iOS Keychain and Android SharedPreferences for storing tokens. In the web app, we use localStorage. The error occurs both in the web and the native apps as well.

Nothing we’ve tried in the last few months has worked:
 - We have a refresh token lifetime of 1 year, without idle refresh token expiration
 - Rotation overlap period of 30 seconds
 - Upgrading the Auth0 client to the latest version (2.11.0)
 - Wrapping the getAccessTokenSilently call in an async-lock block to avoid potential concurrency issues
 - Even adding a small delay before calling getAccessTokenSilently

**Comment by gyaneshgouraw** [comment]
We’ve recently released a fix in the underlying base library used by this SDK that addresses issues related to reused refresh tokens:  https://github.com/auth0/auth0-spa-js/pull/1503

This fix will be included in an upcoming release of the auth0-react SDK as well.

It’s worth noting that reused refresh token issues can have multiple root causes, ranging from tenant configuration to how a client structures its refresh token logic. The PR linked above specifically addresses scope-related issues that could lead to refresh token reuse.

Once the fix is shipped in the auth0-react SDK, I’ll follow up with an update here.

**Comment by LA-Johan** [comment]
@gyaneshgouraw-okta reading through the PR, would that fix the issue we're facing? Looking at our code we don't change the scope dynamically, it's always the same.

**Comment by yogeshchoudhary147** [comment]
Hey @LA-Johan and @francosomosfin,

We've just released **auth0-react v2.14.0** (with auth0-spa-js v2.15.0) which includes fixes for refresh token reuse issues:

1. **Refresh token synchronization** ([#1503](https://github.com/auth0/auth0-spa-js/pull/1503)) - Ensures refresh tokens are properly synced across cache entries during rotation
2. **Token expiration preservation** ([#1529](https://github.com/auth0/auth0-spa-js/pull/1529)) - Prevents expired tokens from being served after rotation

Could you upgrade to v2.14.0 and let us know if the issue persists?

**If the issue continues**, please share any patterns you notice in the Auth0 logs (timing, user actions, etc.) to help us investigate further.

**Comment by yogeshchoudhary147** [comment]
Hi @LA-Johan, following up on the above. Please let us know if upgrading to v2.14.0 resolved the issue for you. If it still persists, sharing any relevant patterns from your Auth0 logs like error codes and timing between requests would help us investigate further.

**Comment by LA-Johan** [comment]
@yogeshchoudhary147 this issue is still happening as of `2.15.0`. Error code `ferrt`. We see a similar issue using the react native package on mobile, though there the error is usually combined with a `Token could not be decoded or is missing in DB` error code `fertft`, which we don't see on web. You can see discussion on the mobile issue [here](https://github.com/auth0/react-native-auth0/issues/1374). 

We have not noticed any particular patterns or timing of this happening other than it being pretty rare, but since our implementation is barebones you might have better logging of our tenant than we do, feel free to access to debug.

Edit: I can't say that this is true for all of our users but anecdotally it seems to happen on page launch / app launch.

**Comment by LA-Johan** [comment]
@yogeshchoudhary147 we seem to be seeing a big uptick of these in the last couple of hours despite no changes or releases on our end.

**Comment by francosomosfin** [comment]
@yogeshchoudhary147 @LA-Johan we are experiencing a lot of these errors in the last 4 hours aprox

**Comment by francosomosfin** [comment]
Before that, the error was still happening

**Comment by LA-Johan** [comment]
As this elevation is happening in our mobile app too I would urge you to look at any shared backend they used, I don't think it's a platform specific issue.

**Comment by LA-Johan** [comment]
The elevated errors were apparently related to [this incident](https://status.auth0.com/incidents/63xknm9ky444). We're back down to our normal level of errors.

**Comment by francosomosfin** [comment]
Hi @yogeshchoudhary147 , any update on this issue?

**Comment by yogeshchoudhary147** [comment]
Hi @LA-Johan and @francosomosfin, we shipped a fix for a concurrent refresh token race condition in `auth0-react` v2.24.1 ([auth0-spa-js#1702](https://github.com/auth0/auth0-spa-js/pull/1702)). This was causing multiple simultaneous `getAccessTokenSilently()` calls at app launch to leave the cache in a bad state and trigger the reuse error. Please upgrade to v2.24.1 and let us know if the issue is resolved.

**Comment by yogeshchoudhary147** [comment]
~~Hi @LA-Johan and @francosomosfin, we shipped a fix for a concurrent refresh token race condition in `auth0-react` v2.24.1 ([auth0-spa-js#1702](https://github.com/auth0/auth0-spa-js/pull/1702)). This was causing multiple simultaneous `getAccessTokenSilently()` calls at app launch to leave the cache in a bad state and trigger the reuse error. Please upgrade to v2.24.1 and let us know if the issue is resolved.~~

**Edit:** PR [auth0-spa-js#1702](https://github.com/auth0/auth0-spa-js/pull/1702) fixes a race condition specific to `useMrrt: true` configurations. Are you using MRRT in your setup?

@LA-Johan your Axios interceptor calls `getAccessTokenSilently()` on every outgoing request. If multiple API calls fire concurrently at mount and the access token is expired at that moment, each interceptor triggers a separate token refresh in parallel, which would cause exactly this error. Can you confirm roughly how many concurrent API calls are made at app launch?

**Comment by francosomosfin** [comment]
Hi @yogeshchoudhary147 , thank you for looking into this and for the recent fixes.

No, we are not using MRRT. Our Auth0Provider sets useRefreshTokens={true}, but we do not set useMrrt, and we use a single audience.
All our getAccessTokenSilently() calls are serialized through a module-level AsyncLock using the same key, so they should not run concurrently within a single app instance. We added this lock before our January 19 comment, but the refresh-token reuse error continued occurring on both web and Capacitor native apps.

We have now upgraded to auth0-react 2.24.1. However, since MRRT is not enabled, our understanding is that auth0-spa-js#1702 does not address our case.

Are there any other known causes we should investigate or additional SDK diagnostics we could enable?

**Comment by LA-Johan** [comment]
As part of trying to get https://github.com/auth0/react-native-auth0/issues/1374 resolved we have added a global singleton that ensures no concurrent requests happen on our end, the issue still persists.
